services:
  app:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "80:5000"
    volumes:
      - ./outputs:/app/outputs 
      - ./db:/app/db 
      - ./templates:/app/templates
      - ./static:/app/static  
  
